language: r
r: bioc-devel
cache: packages
addons:
  apt:
    packages:
      - python3-pip
before_install:
  - pip3 install --user -U pip
  - pip3 install --user jupyter
  - tlmgr install ly1
  - tlmgr install mweights
  - tlmgr install sourcesanspro
  - tlmgr install sourcecodepro
before_script:
  - cd vignettes
  - jupyter nbconvert --template destiny.tplx --to latex Diffusion-Maps.ipynb
  - cd ..
